# Generated by Django 4.1 on 2022-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('email', models.TextField()),
                ('sex', models.TextField()),
                ('dob', models.TextField()),
                ('address', models.TextField()),
                ('cin', models.TextField()),
                ('number', models.TextField()),
                ('cout', models.TextField()),
                ('roomname', models.TextField()),
                ('amount', models.IntegerField()),
                ('mode', models.TextField()),
            ],
        ),
    ]
